### PR TITLE
Front-end UI Improvement

### PR DESCRIPTION
**Pull request by rishi-harti768**
things I have done:
 - changed file structure a bit.
 - broke huge code to smaller components
 - css designed for both light theme and dark theme
 - user name will be stored in localStorage and when they successfully join or create room, we can access it later in chat room
 - the count of member in a room will be shown in members section
 - user name will displayed on top of the members list
 - the user messages and other members messages will be aligned on different direction in message section
 - page is fully responsive that every thing now fits well even on mobile device
 - overall UI like hover effect, click effect is improved

### CODE REVIEW

**Comment by rishi-harti768** [comment]
@navaneethkrishna30 , I'm requesting you to merge my PR.
thank you

**Comment by rishi-harti768** [comment]
hello @navaneethkrishna30 , I have resolved this merge conflict. I would recommend you to merge my PR before others because this contains major of the front-end code as I have compared to others while resolving the conflict issue.

Also, i have added invalid URL handling.

Thank you

**Comment by rishi-harti768** [comment]
@navaneethkrishna30, could you please hurry up.

**Comment by rishi-harti768** [comment]
better be quick @navaneethkrishna30 , I'm waiting since last week.

**Comment by navaneethkrishna30** [comment]
I found out that there is an issue with the frontend having a checkbox that is ginormous and the text is very small. Please take up that issue and resolve it

**Comment by rishi-harti768** [comment]
could you please tell which checkbox are you speaking about. I searched throughout the code and did'nt find any checkbox.
please mention the file name to be accurate.

**Pull request merged**
